version: '3.8'

services:
  app:
    container_name: singuhub-dev-api
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    command: npm run start:dev
    networks:
      - app-network
    restart: unless-stopped


networks:
  app-network:
    driver: bridge
